### PR TITLE
Added missing 'sudo' on docker commands. Fixed markdown (lint)

### PR DESCRIPTION
**Pull request by ondfisk**

### CODE REVIEW

**Review by heoelri — CHANGES_REQUESTED** [review]
please remove sudo for all docker commands - we can add something like "in case your system requires root permissions please use sudo in front of all docker commands"..

**Review by heoelri — CHANGES_REQUESTED** [review]
problems with the numbering in 02-dockerize-apps.md, too

**Comment by ondfisk** [comment]
Changes done

**Comment by ondfisk** [comment]
too much drift

**Pull request closed without merging**
