### PR TITLE
Update 07-cluster-scaling.md

### PR DESCRIPTION
**Pull request by sujitdmello**
Cluster autoscaler required the cluster to be created with VMSS. Standalone cluster cannot be enabled for autoscaling.

### CODE REVIEW

**Comment by heoelri** [comment]
seems like installing the az extension `az extension add --name aks-preview` changes the default behavior.. having the extension installed the cluster will be created with vmss support and you'll not run into this problem.. do you think we should add `az extension add --name aks-preview` to our initial build intructions? i'd like to keep the autoscaler if possible..

**Comment by sujitdmello** [comment]
I tried that but it still threw the error.


________________________________

**Comment by heoelri** [comment]
ok @sujitdmello what about adding `--enable-vmss` directly at the beginning while creating the cluster?

**Comment by sujitdmello** [comment]
I will test it to make sure it does not impact the **az aks scale** command portion of the lab.

**Comment by sujitdmello** [comment]
Operation failed with status: 'Bad Request'. Details: The AvailabilityProfile type of agentpool 'nodepool1' is set to VirtualMachineScaleSets, but the Kubernetes version is 1.11.6 which doesn't support VMSS.

**Comment by desreela** [comment]
One suggestion:
I think we can have this as a separate exercise on day 3/4 where candidates can spin up a new cluster on VMSS to test this.

**Comment by heoelri** [comment]
@desreela yeah.. I agree.. I think that's the easiest solution for now

**Comment by sujitdmello** [comment]
az extension add --name aks-preview
az feature register --name VMSSPreview --namespace Microsoft.ContainerService

az feature list -o table --query "[?contains(name, 'Microsoft.ContainerService/VMSSPreview')].{Name:name,State:properties.state}"

**Wait for status to change to 'registered'**

az provider register --namespace Microsoft.ContainerService

// Now create AKS cluster
az aks create --name $CLUSTER_NAME --resource-group $NAME --node-count 2 \
              --kubernetes-version 1.12.4 --generate-ssh-keys --location $LOCATION --enable-vmss

az aks scale --name $CLUSTER_NAME --resource-group $NAME --node-count 1 **works**.

az aks upgrade --resource-group $NAME -n $CLUSTER_NAME --kubernetes-version 1.12.5 **works**.

az aks update --resource-group $NAME --name $CLUSTER_NAME --enable-cluster-autoscaler --min-count 1 --max-count 3 **works**.

**Comment by heoelri** [comment]
thanks @sujitdmello should we change it that way (it's pretty complicated and hard to understand on day 2) or should we move the autoscaler part (temporarly into the advanced ones)? i think it will become default very soon..

@sujitdmello @desreela @blueflightx7

**Comment by sujitdmello** [comment]
Yeah let’s keep it simple. We can move the autoscaling to its own lab.


________________________________

**Comment by heoelri** [comment]
fixed by removing the autoscaler part temporarily @sujitdmello FYI

**Pull request closed without merging**
